os: linux
services:
  - docker

before_install:
  - sh create_env_file.sh
  - docker build -t paulsbecks/billeroo-backend -f auth-backend/Dockerfile.dev .

script:
  - docker run paulsbecks/billeroo-backend npm run test -- --coverage
