os: linux
services:
  - docker

before_install:
  - cd ./auth-backend && sh create_env_file.sh
  - docker build -t paulsbecks/billeroo-backend -f Dockerfile.dev .

script:
  - docker run paulsbecks/billeroo-backend npm run test -- --coverage
