version: "3"
services:
  proxy:
    restart: "always"
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - 8000:80
  auth-backend:
    restart: "always"
    build:
      dockerfile: Dockerfile
      context: "./auth-backend"
  data-backend:
    restart: "always"
    build:
      dockerfile: Dockerfile
      context: "./data-backend"
