version: "3"
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /usr/billeroo-backend/node_modules
      - .:/usr/billeroo-backend
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /usr/billeroo-backend/node_modules
      - .:/usr/billeroo-backend
    command: ["npm", "run", "test"]
